### PR TITLE
Parsing cURL snippet with content-type multipart/form-data

### PR DESCRIPTION
**Pull request by ashishrout-tech**
Issue: Not able to make a new session from cURL code with content-type set to multipart/form-data

This video demonstrates the issue.

https://github.com/RecipeUI/RecipeUI/assets/77796540/5bc84ac8-49d3-463f-bbd1-2241a9f1853c

This one shows how the application behaves after the changes:

https://github.com/RecipeUI/RecipeUI/assets/77796540/1ec2f01d-4fae-4f61-bef4-0a26f809462e

### CODE REVIEW

**Comment by JeaneC** [comment]
Nice job! Can you add your CURL snippet as a test case?
https://github.com/RecipeUI/RecipeUI/blob/main/packages/utils/curlParser/index.test.ts

You can run this test locally by running 
```
pnpm run utils:test

pnpm run utils:test -- --watch // To watch it
```

**Comment by ashishrout-tech** [comment]
All tests passed. Now adding more tests for form-data type

**Comment by JeaneC** [comment]
@all-contributors please add @ashishrout-tech for code

**Comment by JeaneC** [comment]
Great work, merging it to web. Will let you know when it pushes to desktop (probably later today)

**Pull request merged**
